In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('Countries.csv')

In [5]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [7]:
df[['country','population']]

                country  population
0           Afghanistan    41128771
1               Albania     2775634
2               Algeria    44903225
3               Andorra       79824
4                Angola    35588987
..                  ...         ...
189             Vietnam    98186856
190  West Bank and Gaza     5043612
191               Yemen    33696614
192              Zambia    20017675
193            Zimbabwe    16320537

[194 rows x 2 columns]

In [8]:
#which country has highest population
z=df[df['population']==df['population'].max()]
z

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [ ]:
#country with highest population capital
z[['country','capital_city']]

   country capital_city
75   India    New Delhi

In [12]:
#Which country has the least population
y=df[df['population']==df['population'].min()]
y

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.0,178.0,18.0,...,11312,6.25,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister

In [16]:
#Which country has the highest democratic score top 5
df.sort_values(by='democracy_score',ascending=False,inplace=True)

In [17]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [32]:
#how many regions are there
df['region'].value_counts().count()

np.int64(22)

In [30]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [36]:
#how many countries lie in eastern europe region
df['region'].value_counts()['Eastern Europe']

np.int64(10)

In [38]:
#who is the political leader of second highest populationwise country
df.sort_values(by='population',ascending=False)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.000000,77.000000,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.000000,105.000000,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.000000,-97.000000,4058100.0,...,333287557,28.7037,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.000000,120.000000,623000.0,...,275501339,21.9130,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.000000,70.000000,367230.0,...,235824862,20.4678,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,Monaco,Principality of Monaco,Euro,Monaco,Western Europe,Europe,Monegasque,43.733333,7.400000,NaN,...,36469,33.3333,0,36469,0.00,0.00,Unknown,50.5,Albert II,Sovereign Prince
143,San Marino,Republic of San Marino,Euro,City of San Marino,Southern Europe,Europe,Sammarinese,43.766667,12.416667,23.0,...,33660,33.3333,763,32897,0.00,0.00,Unknown,42.7,Alessandro Mancini,Captain Regent
130,Palau,Republic of Palau,U.S. dollar,Ngerulmud,Micronesia,Oceania,Palauan,7.500000,134.500000,43.0,...,18055,6.2500,3258,14797,0.00,0.00,Unknown,31.7,Thomas Remengesau Jr.,President
119,Nauru,Republic of Nauru,Australian dollar,Yaren,Micronesia,Oceania,Nauruan,-0.533333,166.916667,4.0,...,12668,10.5263,0,12668,0.00,0.00,Unknown,16.3,Lionel Aingimea,President
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.000000,178.000000,18.0,...,11312,6.2500,3900,7412,0.00,0.00,Unknown,21.0,Kausea Natano,Prime Minister

In [43]:
df[df['population']==df['population'].nlargest(2).iloc[1]][['country','political_leader',]]

   country political_leader
34   China       Xi Jinping

In [51]:
df[df['political_leader'].isna()]['country']

27                         Cabo Verde
172                       Timor-Leste
151                   Slovak Republic
190                West Bank and Gaza
161    St. Vincent and the Grenadines
159               St. Kitts and Nevis
160                         St. Lucia
Name: country, dtype: object